Repository when-where/whenwhere-server, pull requests merged in 2023-06, with the labels that each got.

#2 회원가입
  package-lock.json
  package.json
  src/app.js
  src/controllers/auth.js
  src/middlewares/index.js
  src/models/User.js
  src/models/index.js
  src/passport/index.js
  src/passport/localStrategy.js
  src/routes/auth.js
Labels: feat, fix

#4 카카오 소셜 로그인, 로그아웃
  .eslintrc.json
  src/app.js
  src/models/User.js
  src/passport/index.js
  src/passport/kakaoStrategy.js
  src/routes/auth.js
  src/routes/testRoute.js
Labels: feat, setting

#6 로컬 로그인
  .gitignore
  package-lock.json
  package.json
  src/app.js
  src/controllers/auth.js
  src/middlewares/index.js
  src/passport/localStrategy.js
  src/routes/auth.js
  src/routes/testRoute.js
Labels: feat, fix, setting

#8 User 데이터베이스 수정
  src/models/User.js
  src/passport/kakaoStrategy.js
Labels: fix

#12 이메일 인증
  package-lock.json
  package.json
  src/app.js
  src/config/email.js
  src/controllers/auth.js
  src/models/User.js
  src/models/index.js
  src/passport/kakaoStrategy.js
  src/routes/auth.js
  src/utils/schedule.js
Labels: feat

#14 배포를 위한 파일 설정
  package.json
Labels: setting

#16 User 테이블 nickname null로 수정
  src/models/User.js
Labels: fix

#18 이메일 인증 유무 확인 API
  src/controllers/auth.js
  src/middlewares/index.js
  src/routes/auth.js
  src/routes/testRoute.js
Labels: feat

#20 로그인 에러 코드 변경
  src/controllers/auth.js
Labels: refactor
